importScripts('./ngsw-worker.js'); // generated by Angular build process
importScripts('./sw-custom.js');
importScripts("https://unpkg.com/localbase@0.7.5/dist/localbase.dev.js");
let db = new Localbase('db');